import type { ArchitectureGraph } from './architecture'
import type { VisualOperation } from './operations'

export type GeneratorLanguage = 'Python' | 'TypeScript'
export interface GeneratedFile { path: string; content: string; language: GeneratorLanguage; operationIds?: string[] }
export interface LanguageAdapter { language: GeneratorLanguage; create(path: string, name: string): string; rename(content: string, from: string, to: string): string; connect(content: string, importPath: string, symbol?: string): string }

const python: LanguageAdapter = { language: 'Python', create: (path, name) => `"""Generated by Simplicio Canvas."""\n\nclass ${name}:\n    pass\n`, rename: (content, from, to) => content.replace(new RegExp(`\\b${from}\\b`, 'g'), to), connect: (content, importPath, symbol = '') => `${symbol ? `from ${importPath} import ${symbol}` : `import ${importPath}`}\n${content}` }
const typescript: LanguageAdapter = { language: 'TypeScript', create: (_path, name) => `/** Generated by Simplicio Canvas. */\n\nexport class ${name} {}\n`, rename: (content, from, to) => content.replace(new RegExp(`\\b${from}\\b`, 'g'), to), connect: (content, importPath, symbol = 'default') => `import ${symbol} from '${importPath}'\n\n${content}` }

export const adapters: Record<GeneratorLanguage, LanguageAdapter> = { Python: python, TypeScript: typescript }
export function adapterFor(language: string): LanguageAdapter { return language === 'Python' ? python : typescript }

export function generateFiles(graph: ArchitectureGraph, operations: VisualOperation[], language: GeneratorLanguage = 'TypeScript'): GeneratedFile[] {
  const adapter = adapters[language]; const result = new Map<string, GeneratedFile>()
  for (const operation of operations.flatMap((item) => item.type === 'batch' ? item.operations : [item])) {
    if (operation.type === 'create') result.set(operation.node.path, { path: operation.node.path, content: adapter.create(operation.node.path, operation.node.name.replace(/[^A-Za-z0-9_$]/g, '') || 'GeneratedPiece'), language })
    if (operation.type === 'rename') { const current = graph.nodes.find((node) => node.id === operation.nodeId); if (current) { const prior = result.get(current.path) ?? { path: current.path, content: '', language }; result.set(current.path, { ...prior, content: adapter.rename(prior.content, current.name, operation.name) }) } }
    if (operation.type === 'connect') { const target = graph.nodes.find((node) => node.id === operation.edge.to); const source = graph.nodes.find((node) => node.id === operation.edge.from); if (target && source) { const prior = result.get(target.path) ?? { path: target.path, content: '', language }; result.set(target.path, { ...prior, content: adapter.connect(prior.content, `./${source.path.replace(/\.(tsx?|jsx?|py)$/, '')}`, source.name) }) } }
  }
  return [...result.values()].sort((a, b) => a.path.localeCompare(b.path))
}
