import { canApply, type WorkspaceTrust } from './workspace-security'
import { validateWorkspaceMutation, type WorkspaceMutation } from './editor-workspace'

export interface WorkspaceFsAdapter { create(path: string, content?: string): Promise<void>; rename(path: string, nextPath: string): Promise<void>; delete(path: string): Promise<void> }
export interface WorkspaceMutationReceipt { id: string; type: WorkspaceMutation['type'] | 'undo'; path: string; nextPath?: string; accepted: boolean; detail: string; createdAt: string }

export class WorkspaceCrudController {
  private undoStack: Array<() => Promise<void>> = []
  constructor(private readonly trust: WorkspaceTrust, private readonly adapter: WorkspaceFsAdapter) {}
  private absolute(path: string): string { return `${this.trust.root.replace(/[\\/]$/, '')}/${path}` }
  private validate(mutation: WorkspaceMutation): string[] { const errors = validateWorkspaceMutation(mutation); if (!this.trust.trusted) errors.push('workspace trust is required'); if (!errors.length && !canApply(this.trust, this.absolute(mutation.path))) errors.push('path is outside trusted workspace'); if (mutation.nextPath && !errors.length && !canApply(this.trust, this.absolute(mutation.nextPath))) errors.push('destination is outside trusted workspace'); return errors }
  private result(type: WorkspaceMutationReceipt['type'], mutation: WorkspaceMutation, accepted: boolean, detail: string): WorkspaceMutationReceipt { return { id: `workspace-${type}-${Date.now()}`, type, path: mutation.path, nextPath: mutation.nextPath, accepted, detail, createdAt: new Date().toISOString() } }
  async create(path: string, content = ''): Promise<WorkspaceMutationReceipt> { const mutation = { type: 'create' as const, path }; const errors = this.validate(mutation); if (errors.length) return this.result('create', mutation, false, errors.join('; ')); await this.adapter.create(this.absolute(path), content); this.undoStack.push(() => this.adapter.delete(this.absolute(path))); return this.result('create', mutation, true, 'file created') }
  async rename(path: string, nextPath: string): Promise<WorkspaceMutationReceipt> { const mutation = { type: 'rename' as const, path, nextPath }; const errors = this.validate(mutation); if (errors.length) return this.result('rename', mutation, false, errors.join('; ')); await this.adapter.rename(this.absolute(path), this.absolute(nextPath)); this.undoStack.push(() => this.adapter.rename(this.absolute(nextPath), this.absolute(path))); return this.result('rename', mutation, true, 'file renamed') }
  async delete(path: string, confirmation = ''): Promise<WorkspaceMutationReceipt> { const mutation = { type: 'delete' as const, path }; const errors = this.validate(mutation); if (confirmation !== 'DELETE') errors.push('explicit DELETE confirmation required'); if (errors.length) return this.result('delete', mutation, false, errors.join('; ')); await this.adapter.delete(this.absolute(path)); return this.result('delete', mutation, true, 'file deleted; host checkpoint required for undo') }
  async undo(): Promise<WorkspaceMutationReceipt> { const inverse = this.undoStack.pop(); if (!inverse) return { id: `workspace-undo-${Date.now()}`, type: 'undo', path: '', accepted: false, detail: 'nothing to undo', createdAt: new Date().toISOString() }; await inverse(); return { id: `workspace-undo-${Date.now()}`, type: 'undo', path: '', accepted: true, detail: 'last mutation undone', createdAt: new Date().toISOString() } }
}
