import * as THREE from 'three'
import { MapControls } from 'three/examples/jsm/controls/MapControls.js'
import { DragControls } from 'three/examples/jsm/controls/DragControls.js'
import { buildArchitectureGraph, LAYERS, PIECES, type ArchitectureGraph, type ArchitectureNode, type ArchitectureEdge } from './domain/architecture'
import { SIMPLICIO_LOOP_FILES } from './example'
import { analyzeProject, sourceLines, type DocumentedFlow, type ProjectAnalysis, type SourceFileInput } from './domain/analyzer'
import { editorMode } from './domain/project-access'
import { nextHandToolState } from './domain/hand-tool'
import { nextCameraView, type CameraView } from './domain/camera-view'
import { responsiveLayout } from './domain/responsive-layout'
import { DEFAULT_WORKSPACE, IDE_ACTIVITIES, nextActivity, type ActivityId } from './domain/ide-shell'
import { normalizeGitHubRepository } from './domain/github-import'
import { ACTIVE_LOCALES, ALL_LOCALES, isRtlLocale, localeLabel, t, type Locale } from './domain/i18n'
import { PUBLIC_DEMO_POLICY } from './domain/demo-policy'
import { buildExplorerTree, createEditorState, openEditorFile, updateEditorContent, markEditorSaved, type ExplorerEntry } from './domain/editor-workspace'
import { createRunSession, startRunSession, type LaunchConfiguration } from './domain/run-debug'
import { shouldRequirePullRequest, type SourceControlSnapshot } from './domain/source-control'
import { BrowserTerminalAdapter } from './domain/terminal-adapter'
import { DEFAULT_PREFERENCES, searchCommands, type PaletteCommand } from './domain/workspace-preferences'
import { parseSemanticZoomQuery, semanticLabel, semanticLevel, serializeSemanticZoomQuery, type SemanticZoomLevel } from './domain/semantic-zoom'
import { focusFrame } from './domain/explorer-controls'
import { parseMapperFlowArtifact, type MapperFlowArtifact } from './domain/mapper-artifacts'
import { ONBOARDING_STEPS, nextOnboarding, resetOnboarding, type OnboardingProgress } from './domain/onboarding'
import { analyzeDependencies, dependencySeverity, enrichDependencyReport, type DependencyReport } from './domain/dependency-intelligence'
import { createPolicyBaseline, DEFAULT_LAYER_POLICY, evaluatePolicy, policyToSarif, type PolicyFinding } from './domain/architecture-policy'
import { createTelemetryEvent, evaluateSlo, exportSloReport, recordTelemetry, deleteTelemetry, type SloReport, type TelemetryStore } from './domain/telemetry'
import { proposeEdgeReversal } from './domain/edge-refactor'
import { createWorkspaceSnapshot } from './domain/workspace-recovery'
import { createCacheKey, inspectWorkspaceCache, LocalStorageCacheAdapter, repairWorkspaceCache, saveWorkspaceCache, type CacheInspection } from './domain/workspace-cache'
import { SIMPLICIO_LANDSCAPE_FIXTURE, summarizeWorkspaceLandscape } from './domain/multi-repo'
import './style.css'
import './analysis.css'

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
  <header><div class="brand"><span class="mark">S/</span><div><b>SIMPLICIO CANVAS</b><small>software assembly space · alpha 01</small></div></div>
  <div class="actions"><button id="open-github">⑂ GITHUB</button><label class="mapper" id="import-map-label">IMPORTAR MAPA<input id="mapper-file" type="file" accept=".json,application/json"></label><button id="open-project" class="folder">＋ ABRIR PASTA</button><label class="fallback" title="Modo leitura quando o navegador não permite gravar"><input id="folder" type="file" webkitdirectory multiple>IMPORTAR S/ GRAVAÇÃO</label><button id="reset">EXEMPLO SIMPLICIO-LOOP</button><label class="locale-picker" title="Idioma da interface"><span>文</span><select id="locale-select" aria-label="Idioma da interface">${ALL_LOCALES.map((item)=>`<option value="${item.code}" ${ACTIVE_LOCALES.includes(item.code as typeof ACTIVE_LOCALES[number])?'':'disabled'}>${item.label}${ACTIVE_LOCALES.includes(item.code as typeof ACTIVE_LOCALES[number])?'':' · SOON'}</option>`).join('')}</select></label></div></header>
  <main><nav class="activity-bar" aria-label="Ferramentas do workspace">${IDE_ACTIVITIES.map((item,index)=>`<button data-activity="${item.id}" class="${index===0?'active':''}" title="${item.label}" aria-label="${item.label}">${item.icon}</button>`).join('')}<span></span><button title="Conta" aria-label="Conta">◎</button><button title="Configurações" aria-label="Configurações">⚙</button></nav><aside id="workspace-sidebar"><div class="side-title"><span id="side-title">EXPLORER</span><button id="side-close" aria-label="Fechar painel">×</button></div><div id="activity-content"><div class="workspace-root"><b>⌄ ${DEFAULT_WORKSPACE.repository.toUpperCase()}</b><a href="${DEFAULT_WORKSPACE.url}" target="_blank" rel="noreferrer">◉ ${DEFAULT_WORKSPACE.owner}/${DEFAULT_WORKSPACE.repository}</a><small>snapshot local seguro · exemplo padrão</small></div><p class="eyebrow">CAMADAS</p><div id="legend"></div><p class="eyebrow gap">LINGUAGENS</p><div id="languages"><span class="muted">Abra uma pasta para analisar</span></div><p class="eyebrow gap">PEÇAS</p><div id="pieces"></div></div></aside>
  <section id="stage"><div class="editor-tabs"><button class="active"><span>◈</span> architecture.canvas <i>×</i></button><button><span>{ }</span> run_use_case.py <i>×</i></button><div class="editor-actions-mini">⋯</div></div><canvas></canvas><div id="minimap" aria-label="Minimapa da arquitetura"></div><div class="stage-label"><span>ARQUITETURA / VISÃO EXPLODIDA</span><strong id="project-name">wesleysimplicio/simplicio-loop · snapshot seguro</strong></div>
  <div id="project-hud" class="project-hud"><header><span>PROJECT TELEMETRY</span><button id="view-toggle" title="Alternar vista aérea (T)">⌗ TOP</button></header><div class="hud-grid"><span><b id="hud-files">21</b>arquivos</span><span><b id="hud-imports">20</b>conexões</span><span><b id="hud-flows">0</b>fluxos README</span><span><b id="hud-languages">6</b>camadas</span></div><div class="edge-legend"><i class="import-edge"></i>import/código <i class="readme-edge"></i>fluxo documentado</div><div id="insights-panel" class="insights-panel" aria-live="polite"><span>POLICY · aguardando análise</span><span>DEPENDENCIES · aguardando análise</span></div><div id="slo-panel" class="slo-panel" aria-live="polite"><span>DIAGNÓSTICOS LOCAIS · telemetria desligada</span><button id="telemetry-consent" type="button">ATIVAR LOCAL</button></div><div id="recovery-panel" class="recovery-panel" aria-live="polite"><span>RECOVERY · aguardando snapshot</span></div><div id="landscape-panel" class="landscape-panel" aria-live="polite"><span>LANDSCAPE · 4 repositórios · 2 disponíveis</span></div><div class="roadmap-controls" aria-label="Próximas capacidades"><button disabled title="Em breve: agrupamento por pasta e módulo">▦ GROUP <small>SOON</small></button><button id="flow-toggle" title="Alternar fluxos documentados">⇢ FLOW</button><button title="Interface instantânea em quinze idiomas">文 15 LANGS</button><button title="Evidências no README">▧ GALLERY</button></div></div>
  <div id="scan-status" class="scan-status" hidden><i></i><span>ANALISANDO PROJETO…</span></div><button id="help-trigger" class="help-trigger" title="Atalhos">H</button><div id="help" class="help" hidden><button id="help-close">×</button><b>CONTROLES DO UNIVERSO</b><span><kbd>arraste vazio</kbd> mover pelo projeto</span><span><kbd>arraste peça</kbd> organizar o desenho</span><span><kbd>scroll</kbd> aproximar / afastar</span><span><kbd>H</kbd> ferramenta mão</span><span><kbd>T</kbd> vista aérea</span><span><kbd>clique</kbd> abrir terminal e conexões</span></div><div class="hint">arraste o vazio para mover · T vista aérea · H mão</div><div class="bottom-panel"><div class="panel-tabs"><b>PROBLEMS <small>0</small></b><b>OUTPUT</b><b>DEBUG CONSOLE</b><b class="active">TERMINAL</b><span></span><button aria-label="Novo terminal">＋</button><button aria-label="Fechar terminal">×</button></div><code><i>➜</i> simplicio-loop <em>git:(main)</em> <span>simplicio-mapper scan . --visualization</span></code></div></section>
  <aside id="inspector" class="inspector"><div class="sheet-grip"></div><button id="inspector-close" aria-label="Fechar inspector">×</button><p class="eyebrow">INSPECTOR</p><div id="selection"><div class="empty-orbit">◌</div><h2>Selecione uma peça</h2><p>Veja o papel, caminho e encaixes do objeto.</p></div></aside></main>
  <footer><span class="branch">⑂ main*</span><span id="stats"></span><span><i class="pulse"></i> FLUXOS ATIVOS</span><span>Ln 1, Col 1 · UTF-8 · {} TypeScript</span><span>LOCAL-FIRST</span></footer><div id="github-dialog" class="github-dialog" hidden><form><button type="button" id="github-close" aria-label="Fechar">×</button><p class="eyebrow">IMPORTAR DO GITHUB</p><h2>Clone local + Mapper</h2><p>O repositório público será clonado em <code>.simplicio/workspaces</code> e analisado localmente.</p><label>REPOSITÓRIO<input id="github-repository" value="wesleysimplicio/simplicio-loop" autocomplete="off"></label><button id="github-submit" type="submit">CLONAR E VISUALIZAR</button><small id="github-status">A leitura básica funciona mesmo se o simplicio-mapper não estiver disponível.</small></form></div><div id="command-palette" class="command-palette" hidden><div class="command-dialog" role="dialog" aria-label="Command palette"><input id="command-input" autocomplete="off" placeholder="Search commands"><div id="command-results"></div><small>Esc para fechar · Ctrl+K / Ctrl+P</small></div></div><div id="onboarding" class="onboarding" hidden role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><div class="onboarding-card"><span class="eyebrow">GUIA LOCAL-FIRST · SIMPLICIO-LOOP</span><h2 id="onboarding-title"></h2><p id="onboarding-description"></p><small id="onboarding-progress"></small><div><button id="onboarding-next" type="button">PRÓXIMO</button><button id="onboarding-skip" type="button">PULAR</button><button id="onboarding-reset" type="button">REINICIAR</button></div></div></div>`
document.documentElement.classList.toggle('demo-mode', __DEMO_MODE__)
if (location.protocol === 'https:' && 'serviceWorker' in navigator) navigator.serviceWorker.register(new URL('sw.js', document.baseURI), { scope: './' }).catch(() => undefined)
document.querySelector('#project-hud')?.insertAdjacentHTML('beforeend','<div id="flow-provenance" class="flow-provenance" hidden></div><div id="flow-list" class="flow-list" aria-label="Fluxos documentados"></div>')
if (__DEMO_MODE__) {
  document.querySelectorAll<HTMLInputElement | HTMLButtonElement>('#mapper-file, #folder, #open-github, #open-project, #reset').forEach((control) => { control.disabled = true })
  document.addEventListener('keydown', (event) => { if (event.key.toLowerCase() === 'h') event.stopImmediatePropagation() }, true)
  document.addEventListener('click', (event) => {
    const target = event.target instanceof Element ? event.target : null
    if (target?.closest('#open-project, #open-github, #github-submit, #reset, #help-trigger, #save-source')) { event.preventDefault(); event.stopImmediatePropagation() }
  }, true)
  document.addEventListener('change', (event) => {
    const target = event.target instanceof Element ? event.target : null
    if (target?.closest('#folder, #mapper-file')) { event.preventDefault(); event.stopImmediatePropagation() }
  }, true)
  document.addEventListener('submit', (event) => { event.preventDefault(); event.stopImmediatePropagation() }, true)
}

let currentLocale: Locale = (localStorage.getItem('simplicio-canvas.locale') as Locale | null) ?? 'pt-BR'
if (!ACTIVE_LOCALES.includes(currentLocale)) currentLocale = 'pt-BR'
const localeSelect = document.querySelector<HTMLSelectElement>('#locale-select')!
localeSelect.value = currentLocale
function applyLocale(locale: Locale) {
  currentLocale = locale; localStorage.setItem('simplicio-canvas.locale', locale); document.documentElement.lang = locale; document.documentElement.dir = isRtlLocale(locale) ? 'rtl' : 'ltr'
  const setText = (selector: string, key: string) => { const element = document.querySelector(selector); if (element) element.textContent = t(locale, key) }
  const setLabelText = (selector: string, key: string) => { const element = document.querySelector(selector); if (!element) return; const textNode = Array.from(element.childNodes).find((node) => node.nodeType === Node.TEXT_NODE); if (textNode) textNode.textContent = t(locale, key); else element.insertBefore(document.createTextNode(t(locale, key)), element.firstChild) }
  setText('#open-github', 'github'); setLabelText('#import-map-label', 'importMap'); setText('#open-project', 'openFolder'); setText('#reset', 'reset')
  setText('#side-title', 'explorer'); setText('#project-hud > header > span', 'telemetry'); setText('#inspector > .eyebrow', 'inspector')
  const eyebrows = document.querySelectorAll('#workspace-sidebar .eyebrow'); if (eyebrows[0]) eyebrows[0].textContent = t(locale, 'layers'); if (eyebrows[1]) eyebrows[1].textContent = t(locale, 'languages'); if (eyebrows[2]) eyebrows[2].textContent = t(locale, 'pieces')
  const hudLabels = document.querySelectorAll<HTMLElement>('.hud-grid span'); [t(locale, 'files'), t(locale, 'connections'), t(locale, 'flows'), t(locale, 'layersCount')].forEach((label, index) => { const item = hudLabels[index]; if (item) { const value = item.querySelector('b'); if (value) value.textContent = value.textContent ?? ''; const textNode = Array.from(item.childNodes).find((node) => node.nodeType === Node.TEXT_NODE); if (textNode) textNode.textContent = label; else item.appendChild(document.createTextNode(label)) } })
  const terminalTab = document.querySelector('.panel-tabs b.active'); if (terminalTab) terminalTab.childNodes[0].textContent = t(locale, 'terminal')
  const footer = document.querySelector('footer > span:last-child'); if (footer) footer.textContent = t(locale, 'localFirst')
  const selectionTitle = document.querySelector('#selection h2'); if (selectionTitle) selectionTitle.textContent = t(locale, 'selectPiece')
}
localeSelect.addEventListener('change', () => applyLocale(localeSelect.value as Locale)); applyLocale(currentLocale)
const onboardingKey = 'simplicio-canvas.onboarding.v1'
let onboarding: OnboardingProgress = (() => { try { const parsed = JSON.parse(localStorage.getItem(onboardingKey) ?? '') as OnboardingProgress; return parsed?.version === 1 ? parsed : { ...resetOnboarding(), state: 'active' } } catch { return { ...resetOnboarding(), state: 'active' } } })()
const onboardingDialog = document.querySelector<HTMLElement>('#onboarding')!
function persistOnboarding() { localStorage.setItem(onboardingKey, JSON.stringify(onboarding)) }
function renderOnboarding() { const step = ONBOARDING_STEPS[onboarding.step] ?? ONBOARDING_STEPS[0]; document.querySelector('#onboarding-title')!.textContent = step.title; document.querySelector('#onboarding-description')!.textContent = `${step.description} · alvo ${step.target}`; document.querySelector('#onboarding-progress')!.textContent = `${onboarding.step + 1}/${ONBOARDING_STEPS.length} · progresso local`; onboardingDialog.hidden = onboarding.state !== 'active'; document.querySelector<HTMLButtonElement>('#onboarding-next')!.textContent = onboarding.step + 1 >= ONBOARDING_STEPS.length ? 'CONCLUIR' : 'PRÓXIMO' }
document.querySelector('#onboarding-next')!.addEventListener('click', () => { onboarding = nextOnboarding(onboarding); persistOnboarding(); renderOnboarding() })
document.querySelector('#onboarding-skip')!.addEventListener('click', () => { onboarding = { ...onboarding, state: 'skipped' }; persistOnboarding(); renderOnboarding() })
document.querySelector('#onboarding-reset')!.addEventListener('click', () => { onboarding = { ...resetOnboarding(), state: 'active' }; persistOnboarding(); renderOnboarding() })
renderOnboarding()
addEventListener('keydown', (event) => {
  if (event.key !== 'Escape') return
  const palette = document.querySelector<HTMLElement>('#command-palette')
  const github = document.querySelector<HTMLElement>('#github-dialog')
  const onboardingLayer = document.querySelector<HTMLElement>('#onboarding')
  const inspector = document.querySelector<HTMLElement>('#inspector')
  const helpLayer = document.querySelector<HTMLElement>('#help')
  if (palette && !palette.hidden) { event.preventDefault(); event.stopImmediatePropagation(); palette.hidden = true; return }
  if (github && !github.hidden) { event.preventDefault(); event.stopImmediatePropagation(); github.hidden = true; return }
  if (onboardingLayer && !onboardingLayer.hidden) { event.preventDefault(); event.stopImmediatePropagation(); onboarding = { ...onboarding, state: 'skipped' }; persistOnboarding(); renderOnboarding(); return }
  if (helpLayer && !helpLayer.hidden) { event.preventDefault(); event.stopImmediatePropagation(); helpLayer.hidden = true; handMode = false; applyHandMode?.(); return }
  if (inspector?.classList.contains('open')) { event.preventDefault(); event.stopImmediatePropagation(); inspector.classList.remove('open') }
}, true)
const canvas = document.querySelector('canvas')!; const scene = new THREE.Scene(); scene.background = new THREE.Color('#07100f'); scene.fog = new THREE.FogExp2('#07100f', .018)
const camera = new THREE.PerspectiveCamera(42, 1, .1, 300); camera.position.set(18, 18, 29)
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.shadowMap.enabled = true
const controls = new MapControls(camera, canvas); controls.enableDamping = true; controls.target.set(10, 0, 1); controls.maxPolarAngle = Math.PI / 2.05
scene.add(new THREE.HemisphereLight('#d6fff5', '#06100d', 2.2)); const key = new THREE.DirectionalLight('#fff1d4', 4); key.position.set(8, 18, 10); key.castShadow = true; scene.add(key)
const grid = new THREE.GridHelper(60, 60, '#19352f', '#10241f'); scene.add(grid)
let group = new THREE.Group(); scene.add(group); const raycaster = new THREE.Raycaster(); const pointer = new THREE.Vector2(); const meshNodes = new Map<THREE.Object3D, ArchitectureNode>(); const clickableNodes = new Map<THREE.Object3D, ArchitectureNode>(); const edgeObjects = new Map<THREE.Object3D, ArchitectureEdge>(); const nodeSprites=new Map<THREE.Object3D,THREE.Sprite>(); const writableHandles=new Map<string,FileSystemFileHandle>(); let dragControls:DragControls|undefined; let analysis: ProjectAnalysis | undefined; let latestGraph: ArchitectureGraph | undefined; let latestDocumented: Array<{ from: string; to: string }> = []; let editorState = createEditorState(); let mapperFlowArtifact:MapperFlowArtifact|undefined; let handMode=false; let flowVisible=true; let zoomLevel:SemanticZoomLevel=0; let zoomStateInitialized=false; const requestedZoom=parseSemanticZoomQuery(location.search); const activeLayers = new Set<string>(); let cameraView:CameraView='perspective';const perspectivePosition=new THREE.Vector3();const perspectiveTarget=new THREE.Vector3(); let latestPolicyFindings: PolicyFinding[] = []; let latestDependencyReport: DependencyReport | undefined; let latestSloReport: SloReport | undefined; let telemetryStore: TelemetryStore = { consent: localStorage.getItem('simplicio-canvas.telemetry-consent') === 'granted' ? 'granted' : 'denied', events: [] }

function updateInsights(graph: ArchitectureGraph, current?: ProjectAnalysis) {
  latestPolicyFindings = evaluatePolicy(graph, DEFAULT_LAYER_POLICY)
  latestDependencyReport = enrichDependencyReport(analyzeDependencies(current?.files ?? []), current?.files ?? [])
  const critical = latestDependencyReport.dependencies.filter((item) => dependencySeverity(item) === 'critical').length
  const warnings = latestDependencyReport.dependencies.filter((item) => dependencySeverity(item) === 'warning').length
  const panel = document.querySelector<HTMLElement>('#insights-panel'); if (!panel) return
  panel.innerHTML = `<span class="insight-${latestPolicyFindings.some((item) => item.severity === 'error') ? 'error' : 'ok'}">POLICY · ${latestPolicyFindings.length ? `${latestPolicyFindings.length} violações` : 'OK'}</span><span class="insight-${critical ? 'error' : warnings ? 'warn' : 'ok'}">DEPENDENCIES · ${latestDependencyReport.dependencies.length} · ${critical} críticas · ${warnings} avisos</span>${!__DEMO_MODE__ ? '<button id="export-sarif" type="button">EXPORTAR SARIF</button><button id="export-baseline" type="button">BASELINE</button>' : ''}`
  document.querySelector<HTMLButtonElement>('#export-sarif')?.addEventListener('click', () => { const blob = new Blob([JSON.stringify(policyToSarif(latestPolicyFindings), null, 2)], { type: 'application/sarif+json' }); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = 'simplicio-canvas-policy.sarif'; anchor.click(); URL.revokeObjectURL(anchor.href) })
  document.querySelector<HTMLButtonElement>('#export-baseline')?.addEventListener('click', () => { const baseline = createPolicyBaseline(DEFAULT_LAYER_POLICY, latestPolicyFindings); const blob = new Blob([JSON.stringify(baseline, null, 2)], { type: 'application/json' }); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = 'simplicio-canvas-policy-baseline.json'; anchor.click(); URL.revokeObjectURL(anchor.href) })
}
function updateSlo(scanMs: number) {
  latestSloReport = evaluateSlo({ scanMs }, undefined, new Date().toISOString())
  const panel = document.querySelector<HTMLElement>('#slo-panel'); if (!panel || !latestSloReport) return
  const breaches = Object.values(latestSloReport.status).filter((status) => status === 'breach').length
  const consent = telemetryStore.consent === 'granted'
  panel.innerHTML = `<span class="slo-${breaches ? 'breach' : 'ok'}">SLO · ${breaches ? `${breaches} limites excedidos` : 'dentro dos limites'} · scan ${Math.round(scanMs)}ms</span><button id="telemetry-consent" type="button">${consent ? 'DESATIVAR LOCAL' : 'ATIVAR LOCAL'}</button>${consent && !__DEMO_MODE__ ? '<button id="export-slo" type="button">EXPORTAR SLO</button><button id="clear-telemetry" type="button">LIMPAR</button>' : ''}`
  document.querySelector<HTMLButtonElement>('#telemetry-consent')?.addEventListener('click', () => { telemetryStore = { ...telemetryStore, consent: consent ? 'denied' : 'granted' }; localStorage.setItem('simplicio-canvas.telemetry-consent', telemetryStore.consent); updateSlo(scanMs) })
  document.querySelector<HTMLButtonElement>('#export-slo')?.addEventListener('click', () => { const blob = new Blob([exportSloReport(latestSloReport!)], { type: 'application/json' }); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = 'simplicio-canvas-slo.json'; anchor.click(); URL.revokeObjectURL(anchor.href) })
  document.querySelector<HTMLButtonElement>('#clear-telemetry')?.addEventListener('click', () => { telemetryStore = deleteTelemetry(telemetryStore); updateSlo(scanMs) })
  if (consent) telemetryStore = recordTelemetry(telemetryStore, createTelemetryEvent('scan_completed', { files: analysis?.files.length ?? 0, imports: analysis?.connections.length ?? 0 }))
}
function updateLandscape() { const summary = summarizeWorkspaceLandscape(SIMPLICIO_LANDSCAPE_FIXTURE); const panel = document.querySelector<HTMLElement>('#landscape-panel'); if (!panel) return; panel.innerHTML = `<span>LANDSCAPE · ${summary.repositories.length} repositórios · ${summary.available} disponíveis · ${summary.unavailable} indisponíveis</span><small>${summary.edges.map((edge) => `${edge.fromRepo} → ${edge.toRepo} · ${edge.type}`).join(' · ')}</small>` }
updateLandscape()
const recoveryAdapter = new LocalStorageCacheAdapter(); let recoveryKey = ''; let recoveryInspection: CacheInspection | undefined
function renderRecovery(inspection: CacheInspection) {
  recoveryInspection = inspection; const panel = document.querySelector<HTMLElement>('#recovery-panel'); if (!panel) return
  const actions = !__DEMO_MODE__ && inspection.status !== 'missing' ? '<button id="recovery-restore" type="button">RESTORE</button><button id="recovery-discard" type="button">DISCARD</button><button id="recovery-inspect" type="button">INSPECT</button>' : ''
  panel.innerHTML = `<span class="recovery-${inspection.status === 'valid' ? 'ok' : inspection.status === 'missing' ? 'muted' : 'warn'}">RECOVERY · ${inspection.status}${inspection.reason ? ` · ${inspection.reason}` : ''}</span>${actions}`
  document.querySelector('#recovery-restore')?.addEventListener('click', () => { const layout = inspection.envelope?.snapshot.layout ?? {}; if (latestGraph) { latestGraph.nodes.forEach((node) => { const point = layout[node.id]; if (point) { node.x = point.x; node.z = point.z ?? node.z ?? 0 } }); renderGraph(latestGraph, latestDocumented) }; renderRecovery({ ...inspection, reason: 'snapshot restaurado e layout reaplicado' }) })
  document.querySelector('#recovery-discard')?.addEventListener('click', () => { recoveryAdapter.remove(recoveryKey); renderRecovery(inspectWorkspaceCache(recoveryAdapter, recoveryKey)) })
  document.querySelector('#recovery-inspect')?.addEventListener('click', () => renderRecovery({ ...inspection, reason: inspection.reason ?? 'snapshot checksum e revisão conferidos' }))
}
function persistRecoverySnapshot(graph: ArchitectureGraph, projectName: string, current?: ProjectAnalysis) {
  const canonical = { schema: '1.0', project: { id: projectName, name: projectName }, nodes: graph.nodes.map((node) => ({ id: node.id, kind: 'file' as const, name: node.name, path: node.path, position: { x: node.x, y: 0, z: node.z } })), edges: graph.edges.map((edge) => ({ id: `${edge.from}:${edge.to}`, from: edge.from, to: edge.to, type: 'calls' as const })), provenance: { source: 'simplicio-canvas', generatedAt: new Date().toISOString() }, evidence: [] }
  const snapshot = createWorkspaceSnapshot(canonical as never, Object.fromEntries(graph.nodes.map((node) => [node.id, { x: node.x, y: 0, z: node.z }])), `${projectName}:${current?.files.length ?? graph.nodes.length}`)
  recoveryKey = saveWorkspaceCache(recoveryAdapter, { repository: projectName, revision: snapshot.revision, configuration: 'canvas-default' }, snapshot); renderRecovery(inspectWorkspaceCache(recoveryAdapter, recoveryKey, snapshot.revision))
}

function puzzleGeometry(kind: string) {
  const shape = new THREE.Shape(); const w = 3.6, h = 1.65, r = kind === 'entity' ? .48 : .34
  shape.moveTo(-w/2+r,-h/2); shape.lineTo(-.42,-h/2); shape.absarc(0,-h/2,.42,Math.PI,0,false); shape.lineTo(w/2-r,-h/2)
  shape.quadraticCurveTo(w/2,-h/2,w/2,-h/2+r); shape.lineTo(w/2,-.38); shape.absarc(w/2,.0,.38,-Math.PI/2,Math.PI/2,false); shape.lineTo(w/2,h/2-r)
  shape.quadraticCurveTo(w/2,h/2,w/2-r,h/2); shape.lineTo(-w/2+r,h/2); shape.quadraticCurveTo(-w/2,h/2,-w/2,h/2-r); shape.lineTo(-w/2,.38)
  shape.absarc(-w/2,0,.38,Math.PI/2,-Math.PI/2,true); shape.lineTo(-w/2,-h/2+r); shape.quadraticCurveTo(-w/2,-h/2,-w/2+r,-h/2)
  return new THREE.ExtrudeGeometry(shape,{depth:.34,bevelEnabled:true,bevelSize:.09,bevelThickness:.08,bevelSegments:3})
}
function labelTexture(node: ArchitectureNode) { const c=document.createElement('canvas'); c.width=512;c.height=210;const x=c.getContext('2d')!;x.fillStyle='#091411';x.fillRect(0,0,512,210);x.fillStyle=LAYERS[node.layer].color;x.font='700 21px monospace';x.fillText(node.layer.toUpperCase(),25,38);x.fillStyle='#effbf6';x.font='700 30px sans-serif';x.fillText(node.name.slice(0,24),25,92);x.fillStyle='#78978b';x.font='18px monospace';x.fillText(PIECES[node.kind].label+'  →  '+PIECES[node.kind].tab,25,142);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t }
function focusFlow(fromId:string,toId:string){const from=[...meshNodes.entries()].find(([,node])=>node.id===fromId)?.[0],to=[...meshNodes.entries()].find(([,node])=>node.id===toId)?.[0];if(!from||!to)return;const center=from.position.clone().add(to.position).multiplyScalar(.5);const span=Math.max(from.position.distanceTo(to.position)*1.4,8);controls.target.set(center.x,0,center.z);camera.position.set(center.x+span*.45,Math.max(10,span*.8),center.z+span*.6);camera.lookAt(controls.target);controls.update()}
function renderGraph(graph: ArchitectureGraph, documented: Array<{ from: string; to: string }> = []) {
  scene.remove(group); group = new THREE.Group(); scene.add(group); meshNodes.clear(); clickableNodes.clear(); edgeObjects.clear(); nodeSprites.clear(); dragControls?.dispose(); const byId=new Map<string,THREE.Mesh>(); const edgeMeshes:THREE.Mesh[]=[]
  graph.nodes.forEach((node) => { const material=new THREE.MeshStandardMaterial({color:LAYERS[node.layer].color,roughness:.46,metalness:.12});const mesh=new THREE.Mesh(puzzleGeometry(node.kind),material);mesh.rotation.x=-Math.PI/2;mesh.position.set(node.x,1,node.z);mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.baseY=1;group.add(mesh);meshNodes.set(mesh,node);clickableNodes.set(mesh,node);byId.set(node.id,mesh);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:labelTexture(node),transparent:true}));sprite.scale.set(3.4,1.4,1);sprite.position.set(node.x,2.5,node.z);group.add(sprite);nodeSprites.set(mesh,sprite);clickableNodes.set(sprite,node) })
  const refreshEdge=(tube:THREE.Mesh)=>{const a=byId.get(tube.userData.from)?.position,b=byId.get(tube.userData.to)?.position;if(!a||!b)return;tube.geometry.dispose();const curve=new THREE.CatmullRomCurve3([a.clone().add(new THREE.Vector3(0,.7,0)),a.clone().lerp(b,.5).add(new THREE.Vector3(0,2.4,0)),b.clone().add(new THREE.Vector3(0,.7,0))]);tube.geometry=new THREE.TubeGeometry(curve,24,.035,5,false)}
  const drawEdge=(from:string,to:string,color:string,opacity:number,flow=false)=>{const tube=new THREE.Mesh(new THREE.BufferGeometry(),new THREE.MeshBasicMaterial({color,transparent:true,opacity}));tube.userData={from,to,flow};refreshEdge(tube);edgeMeshes.push(tube);edgeObjects.set(tube,{from,to,type:'calls'});group.add(tube)}
  graph.edges.forEach((edge)=>drawEdge(edge.from,edge.to,'#86ffce',.5));documented.forEach((edge)=>drawEdge(edge.from,edge.to,'#ffcf66',.95,true))
  const flowList=document.querySelector<HTMLElement>('#flow-list'); if(flowList){flowList.innerHTML=documented.map((edge,index)=>{const from=graph.nodes.find((node)=>node.id===edge.from),to=graph.nodes.find((node)=>node.id===edge.to);return `<button data-flow-index="${index}" title="Focar fluxo">⇢ ${from?.name??edge.from} → ${to?.name??edge.to}</button>`}).join('');flowList.querySelectorAll<HTMLButtonElement>('[data-flow-index]').forEach((button)=>button.addEventListener('click',()=>{const edge=documented[Number(button.dataset.flowIndex)];if(edge)focusFlow(edge.from,edge.to)}))}
  const provenance=document.querySelector<HTMLElement>('#flow-provenance'); if(provenance){provenance.hidden=!documented.length;provenance.textContent=documented.length?`FLOW EVIDENCE · ${mapperFlowArtifact?.source??'README static analysis'}`:''}
  const applyLayerFilters=()=>{meshNodes.forEach((node,mesh)=>{const visible=!activeLayers.size||activeLayers.has(node.layer);mesh.visible=visible;const sprite=nodeSprites.get(mesh);if(sprite)sprite.visible=visible});edgeMeshes.forEach((edge)=>{edge.visible=flowVisible || !edge.userData.flow})}
  applyLayerFilters()
  const minimap=document.querySelector<HTMLElement>('#minimap'); if(minimap){const xs=graph.nodes.map((node)=>node.x),zs=graph.nodes.map((node)=>node.z);const minX=Math.min(...xs,0),maxX=Math.max(...xs,1),minZ=Math.min(...zs,0),maxZ=Math.max(...zs,1);minimap.innerHTML=graph.nodes.map((node)=>`<i title="${node.name}" style="left:${((node.x-minX)/(maxX-minX||1))*100}%;top:${((node.z-minZ)/(maxZ-minZ||1))*100}%;--c:${LAYERS[node.layer].color}"></i>`).join('')}
  dragControls=new DragControls([...meshNodes.keys()],camera,canvas);dragControls.enabled=!handMode;dragControls.addEventListener('dragstart',()=>{controls.enabled=false});dragControls.addEventListener('drag',(event)=>{const mesh=event.object;mesh.position.y=1;mesh.userData.baseY=1;const sprite=nodeSprites.get(mesh);if(sprite)sprite.position.set(mesh.position.x,2.5,mesh.position.z);edgeMeshes.forEach(refreshEdge)});dragControls.addEventListener('dragend',(event)=>{controls.enabled=true;event.object.position.x=Math.round(event.object.position.x*2)/2;event.object.position.z=Math.round(event.object.position.z*2)/2;edgeMeshes.forEach(refreshEdge)})
  document.querySelector('#stats')!.textContent=`${graph.nodes.length} OBJETOS · ${graph.edges.length} CONEXÕES · ${new Set(graph.nodes.map(n=>n.layer)).size} CAMADAS`
  document.querySelector('#hud-files')!.textContent=String(graph.nodes.length);document.querySelector('#hud-imports')!.textContent=String(graph.edges.length);document.querySelector('#hud-languages')!.textContent=String(new Set(graph.nodes.map(node=>node.layer)).size)
}
document.querySelector('#legend')!.innerHTML=Object.entries(LAYERS).map(([id,l])=>`<button data-layer="${id}"><i style="--c:${l.color}"></i><span>${l.label}<small>${l.role}</small></span></button>`).join('')
document.querySelector('#pieces')!.innerHTML=Object.entries(PIECES).slice(0,9).map(([id,p])=>`<span class="chip">${p.label}<small>${id==='screen'?'◖':id==='entity'?'◆':'⊕'}</small></span>`).join('')
document.querySelectorAll<HTMLButtonElement>('#legend [data-layer]').forEach((button)=>button.addEventListener('click',()=>{const layer=button.dataset.layer!;if(activeLayers.has(layer))activeLayers.delete(layer);else activeLayers.add(layer);button.classList.toggle('active',activeLayers.has(layer));meshNodes.forEach((node,mesh)=>{const visible=!activeLayers.size||activeLayers.has(node.layer);mesh.visible=visible;const sprite=nodeSprites.get(mesh);if(sprite)sprite.visible=visible})}))
document.querySelector('#minimap')?.addEventListener('click',(event)=>{const map=event.currentTarget as HTMLElement;const rect=map.getBoundingClientRect();const x=(event as MouseEvent).clientX-rect.left;const z=(event as MouseEvent).clientY-rect.top;const nearest=[...meshNodes.entries()].filter(([mesh])=>mesh.visible).sort((a,b)=>Math.hypot(a[0].position.x-x/rect.width*40,a[0].position.z-z/rect.height*24)-Math.hypot(b[0].position.x-x/rect.width*40,b[0].position.z-z/rect.height*24))[0];if(nearest){controls.target.set(nearest[0].position.x,0,nearest[0].position.z);controls.update()}})
function resolveDocumentedFlows(flows: DocumentedFlow[], graph: ArchitectureGraph): Array<{ from: string; to: string }> {
  const find = (label:string) => graph.nodes.find((node) => { const value=label.toLowerCase().replace(/[^a-z0-9]/g,''); const path=node.path.toLowerCase().replace(/[^a-z0-9]/g,''); const name=node.name.toLowerCase().replace(/[^a-z0-9]/g,''); return value.length>2&&(path.includes(value)||name.includes(value)||value.includes(name)) })
  return flows.flatMap((flow)=>{const from=find(flow.source),to=find(flow.target);return from&&to&&from.id!==to.id?[{from:from.id,to:to.id}]:[]})
}
function resolveMapperFlows(artifact: MapperFlowArtifact, graph: ArchitectureGraph): Array<{ from: string; to: string }> {
  const find = (label:string) => graph.nodes.find((node) => node.id===label || node.path===label || node.name.toLowerCase()===label.toLowerCase() || node.path.toLowerCase().includes(label.toLowerCase()))
  return artifact.edges.flatMap((edge)=>{const from=find(edge.from),to=find(edge.to);return from&&to&&from.id!==to.id?[{from:from.id,to:to.id}]:[]})
}
function load(paths:string[],name:string,current?:ProjectAnalysis){
  const scanStarted = performance.now(); analysis=current; const graph=buildArchitectureGraph(paths); const ids=new Map(graph.nodes.map((node)=>[node.path,node.id]))
  if(current) graph.edges=current.connections.filter((edge)=>!edge.external&&ids.has(edge.source)&&ids.has(edge.target)).map((edge)=>({from:ids.get(edge.source)!,to:ids.get(edge.target)!,type:'depends'}))
  const documented=current?resolveDocumentedFlows(current.documentedFlows,graph):mapperFlowArtifact?resolveMapperFlows(mapperFlowArtifact,graph):[];latestGraph=graph;latestDocumented=documented;renderGraph(graph,documented);updateInsights(graph, current);updateSlo(performance.now() - scanStarted);persistRecoverySnapshot(graph, name, current);document.querySelector('#project-name')!.textContent=name
  document.querySelector('#languages')!.innerHTML=current?Object.entries(current.languages).sort((a,b)=>b[1]-a[1]).map(([language,count])=>`<span class="language"><b>${language}</b><small>${count}</small></span>`).join(''):'<span class="muted">Snapshot sem conteúdo</span>'
  if(current) document.querySelector('#stats')!.textContent=`${current.files.length} ARQUIVOS · ${current.connections.length} IMPORTS · ${current.documentedFlows.length} FLUXOS README · ${current.skipped} IGNORADOS`
  if(current){document.querySelector('#hud-files')!.textContent=String(current.files.length);document.querySelector('#hud-imports')!.textContent=String(current.connections.length);document.querySelector('#hud-flows')!.textContent=String(current.documentedFlows.length);document.querySelector('#hud-languages')!.textContent=String(Object.keys(current.languages).length)}else document.querySelector('#hud-flows')!.textContent='0'; if (typeof renderExplorerTree === 'function') renderExplorerTree()
}
function loadExample(){writableHandles.clear();mapperFlowArtifact=undefined;const example=analyzeProject(`${DEFAULT_WORKSPACE.owner}/${DEFAULT_WORKSPACE.repository}`,SIMPLICIO_LOOP_FILES);load(example.files.map(file=>file.path),`${DEFAULT_WORKSPACE.owner}/${DEFAULT_WORKSPACE.repository} · exemplo`,example);if(innerWidth>=850){const selected=[...meshNodes.values()].find(node=>node.path.endsWith('run_use_case.py'))??[...meshNodes.values()][0];if(selected)showNode(selected)}}
loadExample()
document.querySelector<HTMLButtonElement>('#flow-toggle')!.addEventListener('click',()=>{flowVisible=!flowVisible;document.querySelector<HTMLButtonElement>('#flow-toggle')!.classList.toggle('active',flowVisible);group.children.forEach((child)=>{if(child.userData.flow)child.visible=flowVisible})})
function updateSemanticZoom(){const distance=camera.position.distanceTo(controls.target);const scale=Math.max(0,Math.min(1,1-distance/58));zoomLevel=!zoomStateInitialized&&requestedZoom!==undefined?requestedZoom:semanticLevel(scale,zoomLevel);zoomStateInitialized=true;history.replaceState(null,'',`${location.pathname}${serializeSemanticZoomQuery(zoomLevel,location.search)}${location.hash}`);document.documentElement.dataset.semanticZoom=String(zoomLevel);const breadcrumb=document.querySelector<HTMLElement>('.stage-label span');if(breadcrumb)breadcrumb.textContent=`ARQUITETURA / ${semanticLabel(zoomLevel).toUpperCase()}`;nodeSprites.forEach((sprite,mesh)=>{const node=meshNodes.get(mesh);sprite.visible=zoomLevel>=1 && (!activeLayers.size || activeLayers.has(node?.layer??''))})}
controls.addEventListener('change',updateSemanticZoom)
updateSemanticZoom()
if (__DEMO_MODE__) {
  document.body.classList.add('readonly-demo')
  document.querySelectorAll<HTMLInputElement | HTMLButtonElement>('#mapper-file, #folder, #open-github, #open-project, #reset, #github-submit').forEach((control) => { control.disabled = true })
  document.querySelector<HTMLElement>('#import-map-label')?.setAttribute('hidden', 'true')
  document.querySelector<HTMLElement>('.fallback')?.setAttribute('hidden', 'true')
  document.querySelector<HTMLElement>('#github-dialog')?.setAttribute('hidden', 'true')
  const selection = document.querySelector('#selection')!
  const enforceReadonly = () => { selection.querySelectorAll<HTMLTextAreaElement>('textarea').forEach((editor) => { editor.readOnly = !PUBLIC_DEMO_POLICY.canEditSource; editor.disabled = !PUBLIC_DEMO_POLICY.canEditSource }); selection.querySelectorAll<HTMLElement>('.editor-actions').forEach((actions) => { actions.hidden = !PUBLIC_DEMO_POLICY.canSaveSource }); selection.querySelectorAll<HTMLButtonElement>('#save-source').forEach((button) => { button.disabled = !PUBLIC_DEMO_POLICY.canSaveSource }) }
  new MutationObserver(enforceReadonly).observe(selection, { childList: true }); enforceReadonly()
  if (dragControls) dragControls.enabled = PUBLIC_DEMO_POLICY.canMovePieces
}
async function readFolderHandle(directory: FileSystemDirectoryHandle) {
  writableHandles.clear();const inputs:SourceFileInput[]=[]
  const walk=async(handle:FileSystemDirectoryHandle,prefix=''):Promise<void>=>{const iterable=handle as FileSystemDirectoryHandle & {values:()=>AsyncIterable<FileSystemHandle>};for await(const entry of iterable.values()){const path=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.kind==='directory')await walk(entry as FileSystemDirectoryHandle,path);else{const file=await (entry as FileSystemFileHandle).getFile();let content='';if(file.size<=1_000_000)try{content=await file.text()}catch{content=''}inputs.push({path,content,size:file.size});writableHandles.set(path,entry as FileSystemFileHandle)}}}
  await walk(directory);const result=analyzeProject(directory.name,inputs);load(result.files.map(file=>file.path),directory.name,result)
}
async function readGitHubFallback(repository: ReturnType<typeof normalizeGitHubRepository>): Promise<SourceFileInput[]> {
  const treeResponse = await fetch(`https://api.github.com/repos/${repository.owner}/${repository.repository}/git/trees/HEAD?recursive=1`, { headers: { Accept: 'application/vnd.github+json' } })
  if (!treeResponse.ok) throw new Error(`GitHub não respondeu (${treeResponse.status}). Verifique o repositório público e o limite da API.`)
  const tree = await treeResponse.json() as { tree?: Array<{ type: string; path: string; url: string }> }
  const candidates = (tree.tree ?? []).filter((entry) => entry.type === 'blob' && !/^(\.git|node_modules|dist|build|coverage|\.venv|venv)\//.test(entry.path) && !/\.(png|jpe?g|gif|webp|ico|pdf|zip|woff2?|ttf|lock)$/i.test(entry.path)).slice(0, 300)
  const files: SourceFileInput[] = []
  for (const entry of candidates) {
    try {
      const response = await fetch(entry.url, { headers: { Accept: 'application/vnd.github+json' } }); if (!response.ok) continue
      const blob = await response.json() as { encoding?: string; content?: string; size?: number }; if (blob.size && blob.size > 1_000_000 || blob.encoding !== 'base64' || !blob.content) continue
      const bytes = Uint8Array.from(atob(blob.content.replace(/\s/g, '')), (char) => char.charCodeAt(0)); files.push({ path: entry.path, content: new TextDecoder().decode(bytes), size: bytes.byteLength })
    } catch { /* a single unreadable blob must not abort the project */ }
  }
  if (!files.length) throw new Error('O GitHub não retornou arquivos de texto legíveis para este repositório.')
  return files
}
document.querySelector('#open-project')!.addEventListener('click',async()=>{const picker=(window as Window & {showDirectoryPicker?:()=>Promise<FileSystemDirectoryHandle>}).showDirectoryPicker;if(!picker){document.querySelector<HTMLInputElement>('#folder')!.click();return}const status=document.querySelector<HTMLElement>('#scan-status')!;try{status.hidden=false;const directory=await picker();await readFolderHandle(directory)}catch(error){if((error as DOMException).name!=='AbortError')console.error(error)}finally{status.hidden=true}})
document.querySelector<HTMLInputElement>('#folder')!.onchange=async(e)=>{
  writableHandles.clear()
  const browserFiles=Array.from((e.target as HTMLInputElement).files??[]) as Array<File & {webkitRelativePath:string}>;if(!browserFiles.length)return
  const status=document.querySelector<HTMLElement>('#scan-status')!;status.hidden=false;await new Promise(requestAnimationFrame)
  const root=browserFiles[0].webkitRelativePath.split('/')[0];const inputs:SourceFileInput[]=[]
  for(const file of browserFiles){const path=file.webkitRelativePath.split('/').slice(1).join('/')||file.name;let content='';if(file.size<=1_000_000)try{content=await file.text()}catch{content=''}inputs.push({path,content,size:file.size})}
  const result=analyzeProject(root,inputs);load(result.files.map(file=>file.path),root,result);status.hidden=true
}
document.querySelector<HTMLInputElement>('#mapper-file')!.onchange=async(e)=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;const raw=JSON.parse(await file.text()) as unknown;const artifact=parseMapperFlowArtifact(raw);mapperFlowArtifact=artifact;const found=new Set<string>();const visit=(value:unknown)=>{if(Array.isArray(value))value.forEach(visit);else if(value&&typeof value==='object')for(const [key,item] of Object.entries(value)){if((key==='path'||key==='file')&&typeof item==='string'&&/\.[a-z0-9]+$/i.test(item))found.add(item);visit(item)}};visit(raw);load([...found,...artifact.nodes.flatMap((node)=>node.path?[node.path]:[])],`mapper · ${file.name}`)}
document.querySelector('#reset')!.addEventListener('click',loadExample)
const GITHUB_IMPORT_ENDPOINT = location.hostname === 'simpleti.com.br' ? new URL('api/github-import.php', document.baseURI).pathname : '/api/github/import'
const githubDialog=document.querySelector<HTMLElement>('#github-dialog')!,githubInput=document.querySelector<HTMLInputElement>('#github-repository')!,githubStatus=document.querySelector<HTMLElement>('#github-status')!;document.querySelector('#open-github')!.addEventListener('click',()=>{githubDialog.hidden=false;githubInput.focus()});document.querySelector('#github-close')!.addEventListener('click',()=>githubDialog.hidden=true);githubDialog.querySelector('form')!.addEventListener('submit',async event=>{event.preventDefault();let repository;try{repository=normalizeGitHubRepository(githubInput.value)}catch(error){githubStatus.textContent=(error as Error).message;githubStatus.className='error';return}const button=document.querySelector<HTMLButtonElement>('#github-submit')!;button.disabled=true;githubStatus.className='';githubStatus.textContent=`Clonando ${repository.slug} e executando simplicio-mapper…`;try{const response=await fetch('/api/github/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repository:repository.slug})});const payload=await response.json() as {name?:string;files?:SourceFileInput[];mapper?:{available:boolean;detail:string};error?:string};if(!response.ok)throw new Error(payload.error??'Falha no clone');const result=analyzeProject(payload.name??repository.slug,payload.files??[]);load(result.files.map(file=>file.path),`${repository.slug} · GitHub`,result);githubStatus.textContent=payload.mapper?.available?'Clone e Mapper concluídos.':'Clone concluído; análise básica ativa. '+(payload.mapper?.detail??'');setTimeout(()=>githubDialog.hidden=true,900)}catch(error){githubStatus.textContent=(error as Error).message;githubStatus.className='error'}finally{button.disabled=false}})
let activeActivity:ActivityId|null='explorer';const sidebar=document.querySelector<HTMLElement>('#workspace-sidebar')!;const sideTitle=document.querySelector('#side-title')!;const activityContent=document.querySelector<HTMLElement>('#activity-content')!;const explorerContent=activityContent.innerHTML;const activityViews:Record<ActivityId,string>={explorer:explorerContent,search:'<div class="ide-empty"><b>⌕ SEARCH</b><input placeholder="Search files and symbols"><p>Search the mapped workspace without leaving the Canvas.</p></div>','source-control':'<div class="ide-empty"><b>⑂ SOURCE CONTROL</b><button>INITIALIZE REPOSITORY</button><p>Git operations are simulated in this MVP.</p></div>',run:'<div class="ide-empty"><b>▷ RUN AND DEBUG</b><button>RUN MAPPER ANALYSIS</button><p>Launch and debug adapters arrive through the roadmap.</p></div>',extensions:'<div class="ide-empty"><b>▦ EXTENSIONS</b><div class="extension-card"><strong>Simplicio Loop</strong><small>installed · project skill</small></div><div class="extension-card"><strong>Simplicio Mapper</strong><small>workspace visualization provider</small></div></div>'};document.querySelectorAll<HTMLButtonElement>('[data-activity]').forEach(button=>button.addEventListener('click',()=>{const selected=button.dataset.activity as ActivityId;activeActivity=nextActivity(activeActivity,selected);document.querySelectorAll('[data-activity]').forEach(item=>item.classList.toggle('active',item===button&&activeActivity!==null));sidebar.classList.toggle('collapsed',activeActivity===null);if(activeActivity){sideTitle.textContent=IDE_ACTIVITIES.find(item=>item.id===activeActivity)!.label.toUpperCase();activityContent.innerHTML=activityViews[activeActivity]}}));document.querySelector('#side-close')!.addEventListener('click',()=>{activeActivity=null;sidebar.classList.add('collapsed');document.querySelectorAll('[data-activity]').forEach(item=>item.classList.remove('active'))})
function explorerEntryHtml(entry: ExplorerEntry): string { const badges = entry.badges.map((badge) => `<small class="badge ${badge}">${badge}</small>`).join(''); if (entry.kind === 'directory') return `<details open><summary>${escapeHtml(entry.name)}</summary>${(entry.children ?? []).map(explorerEntryHtml).join('')}</details>`; return `<button class="file" data-explorer-path="${escapeHtml(entry.path)}" title="${escapeHtml(entry.path)}">${escapeHtml(entry.name)}${badges}</button>` }
function renderExplorerTree() { const target = document.querySelector<HTMLElement>('#workspace-tree'); if (!target) return; const entries = buildExplorerTree((analysis?.files ?? []).map((file) => ({ path: file.path, size: file.size, language: file.language }))); target.innerHTML = entries.length ? entries.map(explorerEntryHtml).join('') : '<span class="muted">Nenhum arquivo analisado</span>'; target.querySelectorAll<HTMLButtonElement>('[data-explorer-path]').forEach((button) => button.addEventListener('click', () => { const node = [...meshNodes.values()].find((item) => item.path === button.dataset.explorerPath); if (node) showNode(node) })) }
function renderSourceControl() { const target = document.querySelector<HTMLElement>('#source-control-view'); if (!target) return; const snapshot: SourceControlSnapshot = { branch: 'main', ahead: 0, behind: 0, files: [], mainProtected: true, provider: writableHandles.size ? 'local' : 'unavailable' }; target.innerHTML = `<div class="ide-status"><strong>⑂ ${snapshot.branch}</strong><span class="ok">${snapshot.provider === 'local' ? 'workspace autorizado' : 'snapshot somente leitura'}</span><br>${analysis?.files.length ?? 0} arquivos analisados · ${snapshot.ahead} à frente · ${snapshot.behind} atrás<br><span class="warn">${shouldRequirePullRequest(snapshot) ? 'main protegida · alterações exigem Pull Request' : 'governança não detectada'}</span><button class="ide-action" disabled>COMMIT / PUSH · HOST LOCAL</button></div>` }
const defaultLaunch: LaunchConfiguration = { id: 'mapper.scan', name: 'Mapper scan (somente leitura)', type: 'mapper', request: { command: 'simplicio-mapper scan . --visualization', cwd: '/workspace' } }
function renderRunDebug() { const target = document.querySelector<HTMLElement>('#run-debug-view'); if (!target) return; target.innerHTML = `<div class="ide-status"><strong>▷ ${defaultLaunch.name}</strong><span>tipo: ${defaultLaunch.type} · diretório: ${defaultLaunch.request.cwd}</span><br><span class="${__DEMO_MODE__ ? 'warn' : 'ok'}">${__DEMO_MODE__ ? 'modo público: processos desabilitados' : 'host local: confirmação explícita necessária'}</span><button id="run-mapper" class="ide-action" ${__DEMO_MODE__ ? 'disabled' : ''}>${__DEMO_MODE__ ? 'EXECUÇÃO DESABILITADA' : 'INICIAR COM RUN'}</button><div id="run-receipt" class="run-receipt"></div></div>`; const button = target.querySelector<HTMLButtonElement>('#run-mapper'); button?.addEventListener('click', async () => { const session = startRunSession(createRunSession(defaultLaunch, { trusted: true, root: '/workspace' }), 'RUN'); const receipt = await new BrowserTerminalAdapter().run({ ...defaultLaunch.request, confirmation: 'RUN' }); target.querySelector('#run-receipt')!.textContent = `${session.state} · ${receipt.output}` }) }
document.querySelectorAll<HTMLButtonElement>('[data-activity]').forEach((button) => button.addEventListener('click', () => setTimeout(() => { const selected = button.dataset.activity as ActivityId; if (selected === 'explorer' && !document.querySelector('#workspace-tree')) { activityContent.insertAdjacentHTML('beforeend', '<p class="eyebrow gap">ARQUIVOS DO WORKSPACE</p><div id="workspace-tree" class="workspace-tree"></div>'); renderExplorerTree() } if (selected === 'source-control') { activityContent.innerHTML = '<div id="source-control-view"></div>'; renderSourceControl() } if (selected === 'run') { activityContent.innerHTML = '<div id="run-debug-view"></div>'; renderRunDebug() } }, 0)))
setTimeout(() => { if (activeActivity === 'explorer' && !document.querySelector('#workspace-tree')) { activityContent.insertAdjacentHTML('beforeend', '<p class="eyebrow gap">ARQUIVOS DO WORKSPACE</p><div id="workspace-tree" class="workspace-tree"></div>'); renderExplorerTree() } }, 0)
const palette = document.querySelector<HTMLElement>('#command-palette')!; const paletteInput = document.querySelector<HTMLInputElement>('#command-input')!; const paletteResults = document.querySelector<HTMLElement>('#command-results')!
const paletteCommands: PaletteCommand[] = [
  { id: 'canvas.reset', label: 'Reset bundled example', category: 'canvas', keybinding: DEFAULT_PREFERENCES.shortcuts['canvas.open'], run: loadExample },
  { id: 'canvas.explorer', label: 'Focus workspace Explorer', category: 'workspace', run: () => document.querySelector<HTMLButtonElement>('[data-activity="explorer"]')?.click() },
  { id: 'canvas.search', label: 'Search files and symbols', category: 'editor', keybinding: DEFAULT_PREFERENCES.shortcuts['canvas.search'], run: () => document.querySelector<HTMLButtonElement>('[data-activity="search"]')?.click() },
  { id: 'mapper.run', label: 'Open Mapper Run and Debug', category: 'mapper', run: () => document.querySelector<HTMLButtonElement>('[data-activity="run"]')?.click() },
]
function renderPalette(query = '') { paletteResults.innerHTML = ''; searchCommands(paletteCommands, query).forEach((command) => { const item = document.createElement('button'); item.className = 'command-result'; item.innerHTML = `${escapeHtml(command.label)}<small>${escapeHtml(command.category)}${command.keybinding ? ` · ${escapeHtml(command.keybinding)}` : ''}</small>`; item.addEventListener('click', async () => { palette.hidden = true; await command.run() }); paletteResults.append(item) }) }
function openPalette() { palette.hidden = false; paletteInput.value = ''; renderPalette(); paletteInput.focus() }
paletteInput.addEventListener('input', () => renderPalette(paletteInput.value)); palette.addEventListener('click', (event) => { if (event.target === palette) palette.hidden = true }); addEventListener('keydown', (event) => { if ((event.ctrlKey || event.metaKey) && (event.key.toLowerCase() === 'k' || event.key.toLowerCase() === 'p')) { event.preventDefault(); openPalette() } if (event.key === 'Escape' && !palette.hidden) palette.hidden = true }); renderPalette()
function bindExplorerSearch() {
  const input = activityContent.querySelector<HTMLInputElement>('input[placeholder="Search files and symbols"]')
  if (!input || input.dataset.bound) return
  input.dataset.bound = 'true'
  input.addEventListener('input', () => {
    const query = input.value.trim().toLowerCase()
    const visible = new Set<string>()
    meshNodes.forEach((node, mesh) => {
      const match = !query || `${node.name} ${node.path} ${node.layer} ${node.kind}`.toLowerCase().includes(query)
      mesh.visible = match
      nodeSprites.get(mesh)!.visible = match
      if (match) visible.add(node.id)
    })
    group.children.forEach((child) => {
      if (child instanceof THREE.Mesh && child.userData.from && child.userData.to) child.visible = visible.has(child.userData.from) && visible.has(child.userData.to)
    })
    const count = visible.size
    input.setAttribute('aria-label', `${count} matching mapped objects`)
    focusVisibleNodes()
  })
}
function focusVisibleNodes() {
  const points = [...meshNodes.entries()].filter(([mesh]) => mesh.visible).map(([mesh]) => ({ x: mesh.position.x, z: mesh.position.z }))
  if (!points.length) return
  const frame = focusFrame(points); controls.target.set(frame.x, 0, frame.z); camera.position.set(frame.x + frame.span * .55, Math.max(14, frame.span * .9), frame.z + frame.span * .75); camera.lookAt(controls.target); controls.update()
}
document.querySelectorAll<HTMLButtonElement>('[data-activity]').forEach((button) => button.addEventListener('click', () => setTimeout(bindExplorerSearch, 0)))
function escapeHtml(value:string){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function showEdgeProposal(edge: ArchitectureEdge) { const proposal = latestGraph ? proposeEdgeReversal(latestGraph, edge) : undefined; const errors = proposal?.errors.length ? `<p class="error">${proposal.errors.join('; ')}</p>` : '<p class="ok">reversão validada contra ciclos e duplicatas</p>'; document.querySelector('#inspector')!.classList.add('open'); document.querySelector('#selection')!.innerHTML = `<p class="eyebrow">REFATORAÇÃO VISUAL · PREVIEW</p><h2>Reverter conexão</h2><code>${edge.from} → ${edge.to}</code>${errors}<dl><dt>OPERAÇÕES</dt><dd>${proposal?.operations.length ?? 0}</dd><dt>APLICAR</dt><dd>bloqueado no preview</dd></dl><p class="subhead">A proposta é somente leitura; a aplicação exige trust, diff, checkpoint e confirmação APPLY no host.</p>` }
function showNode(node:ArchitectureNode){const file=analysis?.files.find(item=>item.path===node.path);if(file){editorState=openEditorFile(editorState,{path:file.path,content:file.content,language:file.language});}const incoming=analysis?.connections.filter(item=>item.target===node.path&&!item.external)??[];const imports=file?.imports??[];const flows=file?.path.match(/readme/i)?analysis?.documentedFlows??[]:[];const mode=file?editorMode(file.path,new Set(writableHandles.keys())):'download-only';document.querySelector('#inspector')!.classList.add('open');document.querySelector('#selection')!.innerHTML=`<div class="piece-icon" style="--c:${LAYERS[node.layer].color}">⊕</div><p class="tag">${node.layer} / ${node.kind}${file?` / ${file.language}`:''}</p><h2>${node.name}</h2><code>${node.path}</code>${file?`<div class="editor-tabs-local" role="tablist">${editorState.tabs.map((tab)=>`<button class="${tab.id===editorState.activeId?'active':''}" data-editor-tab="${escapeHtml(tab.path)}" role="tab">${escapeHtml(tab.path.split('/').pop()??tab.path)}${tab.dirty?' •':''}</button>`).join('')}</div><dl><dt>LINHAS</dt><dd>${file.lines}</dd><dt>IMPORTS</dt><dd>${imports.length}</dd><dt>IMPORTADO POR</dt><dd>${incoming.length}</dd></dl><p class="subhead">TERMINAL · ${mode==='writable'?'EDITÁVEL':'EXPORTÁVEL'}</p><div class="code-terminal"><header><i></i><i></i><i></i><span>${file.language}</span></header><textarea id="source-editor" spellcheck="false">${escapeHtml(editorState.tabs.find((tab)=>tab.path===file.path)?.content??file.content)}</textarea></div><div class="editor-actions"><button id="save-source">${mode==='writable'?'SALVAR NO PROJETO':'BAIXAR ARQUIVO ALTERADO'}</button><small>${mode==='writable'?'gravação local autorizada':'importe pelo botão Abrir projeto para salvar no disco'}</small></div>${flows.length?`<p class="subhead">FLUXOS DOCUMENTADOS</p><div class="imports documented">${flows.map(flow=>`<span>⇢ ${flow.source} <b>→</b> ${flow.target}</span>`).join('')}</div>`:''}<p class="subhead">DEPENDÊNCIAS</p><div class="imports">${imports.length?imports.map(item=>`<span class="${item.external?'external':''}">→ ${item.specifier}<small>${item.resolvedPath??'pacote externo'}</small></span>`).join(''):'<em>nenhuma detectada</em>'}</div>`:`<dl><dt>ENTRADA</dt><dd>${PIECES[node.kind].socket}</dd><dt>SAÍDA</dt><dd>${PIECES[node.kind].tab}</dd></dl>`}`
  const save=document.querySelector<HTMLButtonElement>('#save-source');if(file&&save)save.onclick=async()=>{const next=document.querySelector<HTMLTextAreaElement>('#source-editor')!.value;const handle=writableHandles.get(file.path);if(handle){const writable=await handle.createWritable();await writable.write(next);await writable.close();file.content=next;file.size=new Blob([next]).size;file.lines=next.split('\n').length;editorState=markEditorSaved(editorState,`file:${file.path}`,next);showNode(node);return}const anchor=document.createElement('a');anchor.href=URL.createObjectURL(new Blob([next],{type:'text/plain'}));anchor.download=file.path.split('/').pop()??file.path;anchor.click();URL.revokeObjectURL(anchor.href)};const editor=document.querySelector<HTMLTextAreaElement>('#source-editor');if(file&&editor){editor.addEventListener('input',()=>{editorState=updateEditorContent(editorState,`file:${file.path}`,editor.value);const tab=document.querySelector<HTMLButtonElement>(`[data-editor-tab="${CSS.escape(file.path)}"]`);if(tab)tab.textContent=`${file.path.split('/').pop()??file.path} •`})};document.querySelectorAll<HTMLButtonElement>('[data-editor-tab]').forEach((tab)=>tab.addEventListener('click',()=>{const next=[...meshNodes.values()].find((item)=>item.path===tab.dataset.editorTab);if(next)showNode(next)}))
}
canvas.addEventListener('click',(e)=>{const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const edgeHit=raycaster.intersectObjects([...edgeObjects.keys()])[0];if(edgeHit){const edge=edgeObjects.get(edgeHit.object);if(edge){showEdgeProposal(edge);return}}const hit=raycaster.intersectObjects([...clickableNodes.keys()])[0];if(hit)showNode(clickableNodes.get(hit.object)!)})
const help=document.querySelector<HTMLElement>('#help')!;const helpTrigger=document.querySelector<HTMLButtonElement>('#help-trigger')!;const applyHandMode=()=>{document.body.classList.toggle('hand-mode',handMode);helpTrigger.classList.toggle('active',handMode);helpTrigger.setAttribute('aria-pressed',String(handMode));helpTrigger.title=handMode?'Modo mão ativo · H ou Esc para sair':'Ativar modo mão · H';if(dragControls)dragControls.enabled=!handMode;if(handMode)help.hidden=false};const toggleHand=()=>{handMode=nextHandToolState(handMode,'h');applyHandMode()};helpTrigger.addEventListener('click',toggleHand);document.querySelector('#help-close')!.addEventListener('click',()=>{help.hidden=true});addEventListener('keydown',(event)=>{if((event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement))return;if(event.key.toLowerCase()==='h'){toggleHand();return}if(event.key.toLowerCase()==='f'){focusVisibleNodes();return}if(event.key==='Escape'&&handMode){handMode=nextHandToolState(handMode,'escape');applyHandMode();help.hidden=true}});applyHandMode()
const viewToggle=document.querySelector<HTMLButtonElement>('#view-toggle')!;const applyCameraView=()=>{if(cameraView==='top'){perspectivePosition.copy(camera.position);perspectiveTarget.copy(controls.target);const box=new THREE.Box3().setFromObject(group);const center=box.getCenter(new THREE.Vector3());const size=box.getSize(new THREE.Vector3());controls.target.copy(center);camera.up.set(0,0,-1);camera.position.set(center.x,Math.max(32,Math.max(size.x,size.z)*1.35),center.z+.01);camera.lookAt(center);viewToggle.textContent='◇ 3D';viewToggle.classList.add('active')}else{camera.up.set(0,1,0);camera.position.copy(perspectivePosition.lengthSq()?perspectivePosition:new THREE.Vector3(18,18,29));controls.target.copy(perspectiveTarget.lengthSq()?perspectiveTarget:new THREE.Vector3(10,0,1));camera.lookAt(controls.target);viewToggle.textContent='⌗ TOP';viewToggle.classList.remove('active')}controls.update()};const toggleCameraView=()=>{cameraView=nextCameraView(cameraView);applyCameraView()};viewToggle.addEventListener('click',toggleCameraView);addEventListener('keydown',(event)=>{if(event.key.toLowerCase()==='t'&&!(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement))toggleCameraView()})
document.querySelector('#inspector-close')!.addEventListener('click',()=>document.querySelector('#inspector')!.classList.remove('open'))
function resize(){const layout=responsiveLayout(innerWidth,innerHeight);document.documentElement.dataset.viewport=layout.mode;document.documentElement.dataset.hud=layout.hud;const el=document.querySelector<HTMLElement>('#stage')!;const width=Math.max(1,el.clientWidth),height=Math.max(1,el.clientHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.5:2));renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix()}addEventListener('resize',resize);addEventListener('orientationchange',resize);resize()
function animate(t:number){controls.update();meshNodes.forEach((n,m)=>m.position.y=(m.userData.baseY??1)+Math.sin(t*.001+n.x)*.045);renderer.render(scene,camera);requestAnimationFrame(animate)}requestAnimationFrame(animate)
githubDialog.querySelector('form')!.addEventListener('submit', async (event) => {
  event.preventDefault(); event.stopImmediatePropagation()
  let repository: ReturnType<typeof normalizeGitHubRepository>
  try { repository = normalizeGitHubRepository(githubInput.value) } catch (error) { githubStatus.textContent = (error as Error).message; githubStatus.className = 'error'; return }
  const button = document.querySelector<HTMLButtonElement>('#github-submit')!; button.disabled = true; githubStatus.className = ''; githubStatus.textContent = `Importando ${repository.slug}…`
  try {
    const response = await fetch(GITHUB_IMPORT_ENDPOINT, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ repository: repository.slug }) })
    const payload = await response.json() as { name?: string; files?: SourceFileInput[]; mapper?: { available: boolean; detail: string }; error?: string }
    if (!response.ok) throw new Error(payload.error ?? 'Ponte local indisponível')
    const result = analyzeProject(payload.name ?? repository.slug, payload.files ?? []); load(result.files.map(file => file.path), `${repository.slug} · GitHub`, result); githubStatus.textContent = payload.mapper?.available ? 'Clone e Mapper concluídos.' : 'Clone concluído; análise básica ativa.'; setTimeout(() => githubDialog.hidden = true, 900)
  } catch {
    try { githubStatus.textContent = 'Lendo a árvore pública do GitHub…'; const files = await readGitHubFallback(repository); const result = analyzeProject(repository.slug, files); load(result.files.map(file => file.path), `${repository.slug} · GitHub`, result); githubStatus.textContent = 'Projeto GitHub carregado pelo navegador; instale o Mapper para enriquecer a leitura.'; setTimeout(() => githubDialog.hidden = true, 900) }
    catch (error) { githubStatus.textContent = (error as Error).message; githubStatus.className = 'error' }
  } finally { button.disabled = false }
}, true)
